package storage

const HEADER = 4

const B_TREE_PAGE_SIZE = 4096
const B_TREE_MAX_KEY_SIZE = 1000
const B_TREE_MAX_VAL_SIZE = 3000
const B_TREE_POINTER_SIZE = 8
const B_TREE_OFFSET_SIZE = 2

const KLEN = 2
const VLEN = 2
const KV_METADATA_SIZE = B_TREE_POINTER_SIZE + KLEN + VLEN
